### ISSUE TITLE
Add a Living Documentation to the Repository

### ISSUE THREAD

**Issue by praveenscience** [praveenscience/Internship-LMS-FrontEnd#1]
The product owner Madhvi has created an excellent set of contents, but that's in the Google Drive. Please create the contents into markdown and use `Documentation.md` as the file name in the root.

You can access the [original documentation folder](https://drive.google.com/folderview?id=1NTbv1lSR02sRipKuwuJQp3ZQ-_3dHoDA) here.

**Comment by praveenscience** [comment]
Claimed by Deepthi. Waiting for them to comment.

**Comment by Amit366** [comment]
So is it just writing the original folder into markdown file??

**Comment by Amit366** [comment]
If yes then I can do it.

**Comment by praveenscience** [comment]
Yep @Amit366 as discussed in Discord. 😁

![image](https://user-images.githubusercontent.com/1830380/103741454-01bfed00-4ff1-11eb-873e-ab859e6179ed.png)

And I guess you didn't see my previous comment:

![image](https://user-images.githubusercontent.com/1830380/103741480-0dabaf00-4ff1-11eb-8817-31f6a0f071b2.png)

**Comment by Deepthi2001** [comment]
@praveenscience Yes I'm taking it up. Thankyou!

**Comment by praveenscience** [comment]
@Deepthi2001 You may start working on it.
