### ISSUE TITLE
Feature request, Links in the readme to open in a new tab

### ISSUE THREAD

**Issue by akshay1027** [praveenscience/Internship-LMS-FrontEnd#104]
**Is your feature request related to a problem? Please describe.**

Links in the readme to open in a new tab so that it is easier for the user to navigate back to GitHub codebase.

**Comment by praveenscience** [comment]
I don't think this is even possible. It's a part of GitHub's Readme design. Don't you feel the same? What's your idea about solving this? Let me know. 🤔

**Comment by akshay1027** [comment]
I found a solution to this on StackOverflow, here is the link: https://stackoverflow.com/questions/3492153/markdown-open-a-new-window-link , but as you are saying its not possible i guess. Can you please share any other solutions, if anything can be done to address this

**Comment by praveenscience** [comment]
@akshay1027 Nopes, we're not doing this. I knew this before. But it's not worth. There's then no difference between having a website inside readme then! I'll file this as a bug / issue or a feature request to GitHub platform. That's what we need to do regarding this. 😊 

Markdown stays Markdown, not breaking any rules there. 👍  Should we close this one now?

**Comment by akshay1027** [comment]
yes, i will close it!
