### ISSUE TITLE
Fix Grammatical Errors in ReadMe.

### ISSUE THREAD

**Issue by aditi1403** [praveenscience/Internship-LMS-FrontEnd#106]
I have made some grammatical edits to the README.md file. Kindly refer to PR #105.

**Comment by praveenscience** [comment]
Alright, you have done a great job, but please next time, ask me before opening a new issue, thanks. 😁 Are you a part of GSSoC or any other programmes?

**Comment by aditi1403** [comment]
Really sorry about that.
Yes I am a GSSoC participant
