### ISSUE TITLE
Instead of "master" should be written "main" in readme 

### ISSUE THREAD

**Issue by SUCHITRAGIRI** [praveenscience/Internship-LMS-FrontEnd#107]
**Describe the Bug**

In the readme file want to update with some changes in this section.
"Why is the master branch so important to not mess with?"
As we know that "master" is replaced with "main" so want to update the readme according to this!

Please assign this issue to me!!

**Comment by praveenscience** [comment]
We're not taking any documentation changes. But feel free to fix it. Won't be putting GSSoC 21 labels. Is that alright? Because this doesn't make any impact for the project.

**Comment by SUCHITRAGIRI** [comment]
Okay, I got your point!
Means related to this PR will not be counted right?

**Comment by praveenscience** [comment]
That's correct, but you get a green square in GitHub! 🚀

**Comment by SUCHITRAGIRI** [comment]
haha!!.. fine

**Comment by praveenscience** [comment]
@SUCHITRAGIRI Not doing this?
