### ISSUE TITLE
Want to add Preloader

### ISSUE THREAD

**Issue by vedant-jain03** [praveenscience/Internship-LMS-FrontEnd#109]
I want to add preloader functionality to the website so that it looks more great.

I will use Lazy, Suspense components.

Preloader

**Comment by vedant-jain03** [comment]
@praveenscience Please assign me if this is valid issue

**Comment by praveenscience** [comment]
This is a good one to consider, but once the design is over, is that alright? But Lazy & Suspense are in beta right? Can you correct me if I am wrong? 🤔

**Comment by vedant-jain03** [comment]
Its alright to assign after design is over
Yes they are beta but I have already contributed using lazy and suspencse in other projects as well in react like kurakoo and doc2pen

**Comment by praveenscience** [comment]
> Its alright to assign after design is over
> Yes they are beta but I have already contributed using lazy and suspencse in other projects as well in react like kurakoo and doc2pen

Okay cool. I am still concerned about the beta nature. But let's see.

**Comment by praveenscience** [comment]
@vedant-jain03 Go ahead and implement if you're ready. I can assign you if you want.

**Comment by GYANANKUR** [comment]
Can I go with this task? It will be really helpful for me to start contributing towards open source for the first time . I will give my best .

**Comment by praveenscience** [comment]
@Mayank-Sh07 and @GYANANKUR please try to team up and take it up?

**Comment by GYANANKUR** [comment]
> Yes sure I am ready to team up

**Comment by Mayank-Sh07** [comment]
Sure! @GYANANKUR lets plan it out and start developing.

**Comment by GYANANKUR** [comment]
Yes @Mayank-Sh07
