### ISSUE TITLE
Organise design folders into docs.

### ISSUE THREAD

**Issue by praveenscience** [praveenscience/Internship-LMS-FrontEnd#119]
We need to get rid of all the content related to documentation work from the root folder. Move everything to `docs` folder:

- `design_admin`
- `designs`
- `flowchart`
- `design-user.md`

**Comment by Spring-dot** [comment]
Assign me.

**Comment by praveenscience** [comment]
Finish it by tomorrow. 😊

**Comment by Spring-dot** [comment]
@praveenscience I have made PR
