### ISSUE TITLE
Feature request: Landing Page

### ISSUE THREAD

**Issue by saimanoharhm** [praveenscience/Internship-LMS-FrontEnd#123]
**Is your feature request related to a problem? Please describe.**

There is no landing page 

**Describe the solution you'd like...**

I would like add a Landing page as per the design with a fully responsive page. 

**Describe alternatives you've considered?**

NO

**Approach to be followed (optional):**

I will use react framework to work on this particular issue.

**Additional context**

**Comment by saimanoharhm** [comment]
@praveenscience Could you please assign this for me.

**Comment by Amankesarwani2202** [comment]
Sir could you please assign to me?

**Comment by praveenscience** [comment]
Sure @Amankesarwani2202, I'll assign it to you! 😊
