### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by AbhipsaGuru1012** [praveenscience/Internship-LMS-FrontEnd#128]
**Is your feature request related to a problem? Please describe.**

Currently the website doesn't have a footer

**Describe the solution you'd like...**

I would like to add the footer in the landing page

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by AbhipsaGuru1012** [comment]
@praveenscience Sir I would like to work on this issue. Please assign it to me

**Comment by praveenscience** [comment]
Okay sure, go on.

**Comment by AbhipsaGuru1012** [comment]
@praveenscience Sir I have made a PR. Please let me know if the changes are okay
