### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by Utkarsh299-tech** [praveenscience/Internship-LMS-FrontEnd#13]
Line in README.md:
**Be awesome and read the follow the guidelines.**

Not sure about this but I think this sentence seems a little bit odd to me in README.md.  If this requires any changes or is there any typo that needs to be fixed? If any, please do tell me. I would be happy to fix it. Thanks!

For your reference, the screenshot has been attached below:

<img width="827" alt="typo" src="https://user-images.githubusercontent.com/60184229/105217275-aa398980-5b79-11eb-97e0-57d54f90535a.png">

**Comment by praveenscience** [comment]
Assigning it to @TeeVenDick.

**Comment by Utkarsh299-tech** [comment]
Oh, that would be great. :)
