### ISSUE TITLE
Implement Apple Style Headers for the App

### ISSUE THREAD

**Issue by praveenscience** [praveenscience/Internship-LMS-FrontEnd#15]
Shall we create an Apple Style headers? Would like it to have the same look at feel. Breakpoint to mobile version at `767px` and above that, i.e., `768px` and above should be full.

Desktop:

![image](https://user-images.githubusercontent.com/1830380/105339564-b9015a00-5bd4-11eb-8c92-a17116bea583.png)

Mobile:

![image](https://user-images.githubusercontent.com/1830380/105339582-bc94e100-5bd4-11eb-9bd0-e14f9113cd80.png)

Let's use right Bootstrap classes for now. We should be using SCSS for the overall application, so I am expecting two files to be created (with `App.scss` for now just including the `Header.scss` (Please don't add extension in `@import`s inside SCSS)):

* `src/components/Header/Header.js`
* `src/styles/Header/Header.scss`
* `src/styles/App.scss`

And two files to be updated:

* `src/components/App.js`
* `src/styles/App.scss`

This is up for grabs for both DevScript & Script Winter of Code folks! 😁

**Comment by pritamp17** [comment]
@praveenscience I would like to work on this issue could you assign me this?

**Comment by praveenscience** [comment]
@pritamp17 Please carry on. Plus, can you tell me you're from SWoC or DWoC or both? 😁

**Comment by pritamp17** [comment]
@praveenscience SWOC

**Comment by nehaparmar99** [comment]
I'd like to work on it.

**Comment by praveenscience** [comment]
@nehaparmar99 Can you tell me you're from SWoC or DWoC or both? 😁

**Comment by nehaparmar99** [comment]
Both sir.

**Comment by praveenscience** [comment]
@nehaparmar99 Thanks ma'am. Just wondering if you checked the above conversation?

**Comment by praveenscience** [comment]
Also, should we have a deadline and competition between @nehaparmar99 and @pritamp17? On the following:

- Who's finishing it first?
- Who's finishing it before this week?
- Who has the best code?

**Comment by nehaparmar99** [comment]
Sure!Sounds fun😁
Also wanted to know if you need the same content as in the apple one, or you need different headings?

**Comment by praveenscience** [comment]
Same design, we'll think about the content later... Have the same one...

**Comment by nehaparmar99** [comment]
This is what I've implemented for now.Do let me know if it requires more styling or changes.

**Comment by praveenscience** [comment]
Sure, will check it out and review it. Wow, that was quick! 😁

**Comment by praveenscience** [comment]
Any progress @nehaparmar99 or @pritamp17?

**Comment by nehaparmar99** [comment]
Hey, I'm so sorry have been a bit busy due to sem exams, I'll make the required changes by tomorrow

**Comment by praveenscience** [comment]
Cool @nehaparmar99 Also, I replied something on the PR, kindly check that and respond me for that! 😁 This is really good so, I really want you to take it up.

**Comment by sherin527** [comment]
I would like to work on this as well

**Comment by praveenscience** [comment]
@sherin527 It's been completed. 😁 Waiting for merging.

**Comment by omrajsharma** [comment]
is this issue has been resolve?

**Comment by praveenscience** [comment]
@omrajsharma Just see the above comments, please? 😅
