### ISSUE TITLE
Regarding DataBase Used in MERN Stack

### ISSUE THREAD

**Issue by Jassi10000** [praveenscience/Internship-LMS-FrontEnd#21]
@praveenscience 
Sir , I would like to bring something in notice , that in the Readme file , you have mentioned that we will be using MERN Stack , in which you mentioned everything right  , except  " M " , According to my knowledge and experience and what all I have learnt from internet and also with people I have worked , I think   " M " in MERN Stack stands for   "Mongo-DB" database and not MySQL , so please can you confirm this thing?

**Comment by ArchishmanSengupta** [comment]
i have the same query. MERN stands for MongoDB, Express, React, Node, after the four key technologies that make up the stack.

MongoDB - document database
Express(.js) - Node.js web framework
React(.js) - a client-side JavaScript framework
Node(.js) - the premier JavaScript web server

Reference website: https://www.mongodb.com/mern-stack

**Comment by praveenscience** [comment]
@Jassi10000 and @ArchishmanSengupta, not sure why it was not clear. Let me quote it from the ReadMe again.

> ### Tech Stack
>
> We are primarily considering JavaScript (sorry, not TypeScript) as the base language. We are using MERN Stack for this, where the tech stack consists of:
>
>* Bootstrap 5 for the Front End
> * React JS with both Class & Functional Components
> * Node JS & Express JS
> * MySQL or PostgreSQL (yet to be decided)

The typical MERN Stack involves MongoDB + ExpressJS + ReactJS + NodeJS. But if you see our product, it really needs a hierarchical database management system not a document oriented. MongoDB doesn't perform well under a lot of situations so we're planning to use MySQL (or MariaDB) or PostgreSQL.

I have also added this point:

> The front end is open sourced, while back end is still closed for outside collaborators. This project contains multiple parts.

So technically, it doesn't matter at the moment, the stack is either MySQL or PostgreSQL in the production environment. Let me know if this clarifies or if you need further clarification.

**Comment by Jassi10000** [comment]
@praveenscience Ohh , now its clear 

Actually , the following  quote is nowhere to be found , that's why we misunderstood

# The typical MERN Stack involves MongoDB + ExpressJS + ReactJS + NodeJS. But if you see our product, it really needs a hierarchical database management system not a document oriented. MongoDB doesn't perform well under a lot of situations so we're planning to use MySQL (or MariaDB) or PostgreSQL.  "

**Comment by praveenscience** [comment]
@Jassi10000 Why da? Why? That was a reply to me. Left le you see the border? That's what is taken from the ReadMe! I guess I have a huge communication gap! 🤦🏻‍♂️ More clarity here:

![image](https://user-images.githubusercontent.com/1830380/106257611-b1fdcb80-6214-11eb-8ebc-cc1d8e0e51e8.png)

**Comment by Jassi10000** [comment]
No issues  sir @praveenscience 😀 ,  I just wanted to improve the documentation in the Readme for others so that they can't get confused like me

**Comment by praveenscience** [comment]
Good thought @Jassi10000! 👍🏻
Keep it up. Thanks! 😅

**Comment by Jassi10000** [comment]
> Good thought @Jassi10000! 👍🏻
> Keep it up. Thanks! 😅

My pleasure sir !! 😄
