### ISSUE TITLE
Add Contributers name and project admin name in the last of the README file

### ISSUE THREAD

**Issue by Ayush7614** [praveenscience/Internship-LMS-FrontEnd#23]
Add Contributers name and project admin name in the last of the README file

![screenshot-github com-2021 02 07-22_11_43](https://user-images.githubusercontent.com/67006255/107153115-d6cf0d00-6991-11eb-8bf5-aa0d555dff2c.png)

Like This

**Comment by CharvyJain** [comment]
Can I work on this ?

**Comment by praveenscience** [comment]
Looks nice... Yea, sure @CharvyJain! 👋🏻

**Comment by Ayush7614** [comment]
First I will talk to you for this and issue was also raised my me so plss assign me first @praveenscience

**Comment by Ayush7614** [comment]
Under DWOC

**Comment by praveenscience** [comment]
@Ayush7614 Done... Unless you comment here, I am unable to put it on you! 😰

**Comment by Ayush7614** [comment]
#24 this is pull for this issue plss review it

**Comment by praveenscience** [comment]
@Ayush7614 Just once in the right place is enough. You have mentioned this 3 times. Not needed, really! 😅

**Comment by praveenscience** [comment]
@CharvyJain I'll get you something else to work on... 😁

**Comment by CharvyJain** [comment]
@praveenscience Yeah! No Problem 😊

**Comment by praveenscience** [comment]
@CharvyJain This hasn't been completed. Can you please do it by today if you can?

**Comment by vismitap** [comment]
Hey! May I work on this issue?

**Comment by praveenscience** [comment]
@vismitap Yea, happy to assign you. See if @CharvyJain is active. If she can't, go with it.

**Comment by CharvyJain** [comment]
@vismitap You can take up the issue.

**Comment by vismitap** [comment]
@CharvyJain Tysm😄. @praveenscience please assign this issue to me!

**Comment by praveenscience** [comment]
Done! @vismitap

**Comment by vismitap** [comment]
The contributor's table would be static and will take up a lot of space. The better way to do this is to have something like this:
![image](https://user-images.githubusercontent.com/47056243/109342082-582f0680-7891-11eb-8f31-26a1c42e0ee8.png)
This is dynamic too so no bot needed! What do you say @praveenscience?

**Comment by praveenscience** [comment]
Good one...
