### ISSUE TITLE
Create a Contributing Readme file similar to Rezume project!

### ISSUE THREAD

**Issue by praveenscience** [praveenscience/Internship-LMS-FrontEnd#3]
I had created something like this before: [Contributing · CatsInTech/Rezume](https://github.com/CatsInTech/Rezume/blob/master/CONTRIBUTING.md).

I want someone to use their creative ideas to create a similar one to this project. We do have a [video](https://youtu.be/GaosMNyPKZc?list=PLO_Y0rsm7b3Yc8FtNhCuD5TO0QM8CnTZj) of the same too! 😁

Make it awwwwesome!

**Comment by akrish4** [comment]
kindly assign me @praveenscience

**Comment by praveenscience** [comment]
Sure, go for it @akrish4! 😁

**Comment by vilsi12** [comment]
Can you assign me

**Comment by Rayman-Sodhi** [comment]
Hello Sir,Can I work on this issue?

**Comment by Utkarsh299-tech** [comment]
Hey everyone, this issue has already been assigned, I think.
Let's wait for another one!

**Comment by Rayman-Sodhi** [comment]
okay so we cannot start working(as an SWOC participant ) if we are not assigned with the task?

**Comment by akrish4** [comment]
#4  PR

**Comment by praveenscience** [comment]
@vilsi12 and @Rayman-Sodhi Please kindly watch [E03: Yes, We're In Trouble when Merge Conflicts Occur! Let's resolve them Gracefully](https://youtu.be/GaosMNyPKZc?list=PLO_Y0rsm7b3Yc8FtNhCuD5TO0QM8CnTZj) so that you know how the GitFlow generally works in Open Source Projects.

**Comment by vismitap** [comment]
Hello Sir, I can see this issue has not been resolved yet and the PR made is also closed by the assignee. So can I give it a try?

**Comment by praveenscience** [comment]
@vismitap Please go ahead...

**Comment by vismitap** [comment]
@praveenscience I have started working on the Readme file and noticed that the reference repository's Readme file contains some nice screenshots. I had a question about that. Should I add the screenshots or are you going to do it with your Mac laptop? Your Screenshots look very neat and nicely edited. It will be great if you provide the screenshots and I add in the Readme file. Or should I go ahead with just text instructions?

I have added Gifs and emojis

**Comment by vismitap** [comment]
After I complete the CONTRIBUTING.md, it has to be linked with the main README.md file also. Should I be doing that as a part of this issue or create a new issue?

**Comment by praveenscience** [comment]
I guessed it. Alright then, I'll give you the images. It's hard, that's why I wanted someone to add it, LoL. Shall we do one thing, we'll do a contribution on both through the Web UI as well as using Command Line? 😁

**Comment by vismitap** [comment]
Yes!
