### ISSUE TITLE
Bug in GitHub AutoAssign Mentors

### ISSUE THREAD

**Issue by muthuannamalai12** [praveenscience/Internship-LMS-FrontEnd#30]
When Running the GitHub action to auto-assign Mentors for every PR it displays a [warning]Resource not accessible by integration` when running against PRs and it does not auto-assign reviewers. Similar to the issue link given below :point_down: 
kentaro-m/auto-assign-action#29

**Comment by muthuannamalai12** [comment]
@praveenscience I would love to work and correct it. Kindly assign me this issue as a part of DWOC.

**Comment by praveenscience** [comment]
@muthuannamalai12 Go ahead. 😁
