### ISSUE TITLE
Modifying and rectifying the welcome bot

### ISSUE THREAD

**Issue by m-code12** [praveenscience/Internship-LMS-FrontEnd#33]

**Comment by m-code12** [comment]
@praveenscience Can I go ahead with this issue?

**Comment by praveenscience** [comment]
What's the problem? What change are you planning to make?

**Comment by m-code12** [comment]
The welcome bot isn't getting triggerred, like it isn't activated
I want to add a community link to the welcome bot
I wanted to ask do we have a separate slack or discord channel for this project, other than dwoc channel?
I can include the link in the welcome bot.

**Comment by m-code12** [comment]
> What's the problem? What change are you planning to make?

Also please could you add the labels?

**Comment by praveenscience** [comment]
Cool then... 😁

**Comment by m-code12** [comment]
Could you share the link of the slack or discord channel?

**Comment by praveenscience** [comment]
@m-code12 I don't think that will be necessary... Do you wanna finish the PR without the link? Happy to merge it... 😁 You're doing an awesome job! 🔥

**Comment by m-code12** [comment]
> @m-code12 I don't think that will be necessary... Do you wanna finish the PR without the link? Happy to merge it... 😁 You're doing an awesome job! 🔥 Add this link if needed: https://praveen.science/.

Thank you for the appreciation😁 @praveenscience 
I have raised a PR, do have a look at it.
