### ISSUE TITLE
Enforce Prettier on commits and builds.

### ISSUE THREAD

**Issue by praveenscience** [praveenscience/Internship-LMS-FrontEnd#36]
I have got this prettier options configured in VS Code. We need a way to ensure that this is there in the build times. If it's not used, including the spaces, etc., the build should fail.

```json
{
  "arrowParens": "avoid",
  "bracketSpacing": true,
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "insertPragma": false,
  "jsxBracketSameLine": false,
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "requirePragma": false,
  "semi": true,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "none",
  "useTabs": false,
  "vueIndentScriptAndStyle": false,
  "filepath": "Untitled-1",
  "parser": "babel"
}
```

This issue is up for grabs for both DWoC and SWoC.

**Comment by sonaliBedade** [comment]
I am a participant of SWoC and I will like to work on this issue. I use both VS Code and Prettier extension and I am familiar with it.  Please assign this issue to me so that I can start working on it.

**Comment by Sloth-Panda** [comment]
@praveenscience sir, can you explain a bit how can we do the same?

**Comment by praveenscience** [comment]
@Sloth-Panda Something like this: https://gist.github.com/jareware/7179093

**Comment by praveenscience** [comment]
@Sloth-Panda and @sonaliBedade Check these out:

* [ESLint checker · Actions · GitHub Marketplace · GitHub](https://github.com/marketplace/actions/eslint-checker)
* [Run ESLint · Actions · GitHub Marketplace · GitHub](https://github.com/marketplace/actions/run-eslint)

I guess these might be a good start...

**Comment by dollyjain51099** [comment]
I would like to work on this issue, @praveenscience kindly assign it to me!

**Comment by praveenscience** [comment]
Hey @dollyjain51099, sure... You can also discuss with @sonaliBedade, as you both know each other! 😅

**Comment by sahildotexe** [comment]
Hey !! I 'm a participant of GSSOC'21, can you assign this issue to me?

**Comment by ampsteric** [comment]
@praveenscience should this issue be closed as you mentioned that we are planning to use something like husky.

**Comment by praveenscience** [comment]
@ampsteric This is totally different. This is for the CI CD Pipeline.

**Comment by ampsteric** [comment]
Ohh okay , actually I saw your comment https://github.com/praveenscience/Internship-LMS-FrontEnd/pull/41#pullrequestreview-610188866 and thought of asking.
