### ISSUE TITLE
Improve ReadMe

### ISSUE THREAD

**Issue by krishna-y2000** [praveenscience/Internship-LMS-FrontEnd#43]
**Is your feature request related to a problem? Please describe.**
There is no section of getting started for developer . How can we start our project in development mode.

**Describe the solution you'd like...**
I will include all the details like clone the repo then go to folder , enter command " cd client -> npm install -> npm start "
Allow me to do this task as part of gssoc'21

**Comment by praveenscience** [comment]
@krishna-y2000 Thanks for adding this. It's actually a part of #38, but yes, this can be a separate one too. What do you think? Did you see the Contributing.md? Should that be changed as well? What say?

**Comment by krishna-y2000** [comment]
@praveenscience  Yes , there should also be made changes . Things to change in Contributing.md file :

1) After cloning project in step 5 there should be command of installing node modules in react folder and then npm start for running the program.
2) In step 11 of uploading files to staging area para. there is no command for creating gitignore file and adding node modules to it for reducing the files size.
Let me know if i am missing something and assign this task to me.
3) Code of conduct is also included in the same file in Contributing.md . It is  the redundant copy of code of conduct  file .

**Comment by praveenscience** [comment]
Okay, sure, what I'll do is, I'll somehow work up a little bit and make the update on the Readme and then we'll do this issue after it's done. Okay? Until then hold on...

**Comment by praveenscience** [comment]
Wait till I finish na? 😅

**Comment by aditisneh** [comment]
Hey @praveenscience Sir, I would like to add a cool banner to this readme. Kindly assign me this. Also I can upload a demo out here, if you say.

**Comment by praveenscience** [comment]
@aditisneh Good idea, please share some quick designs, if it's nice, let's add it to this! 👍  Will give Level2 if it's really nice and creative.

**Comment by aditisneh** [comment]
@praveenscience okay then, working on it.

**Comment by aditisneh** [comment]
https://user-images.githubusercontent.com/56735634/110831759-92040200-82c0-11eb-8e20-af41244bdd3d.mp4

hey have a look

**Comment by starrohan999** [comment]
I think I can update readme.MD file. I found there is a lot of information about past events and things so we can easily delete it and add more info about the current event as it is a part of Gsoc'21. 
Readme file is an attraction point for any beginner or who that is intested in organization project so we have to keep updating and file and precisely.
here are some photos.
![2021-03-12_LI](https://user-images.githubusercontent.com/71714344/110838169-24f46a80-82c8-11eb-88be-cabddba9018f.jpg)
![2021-03-12 (1)_LI](https://user-images.githubusercontent.com/71714344/110838195-2b82e200-82c8-11eb-94c4-22e35f4afae7.jpg)

@praveenscience  can you please assign me this.
@krishna-y2000 I would like to work with you if don't mind
let's do this

**Comment by praveenscience** [comment]
@starrohan999 It's actually a part of #38! 😅

**Comment by praveenscience** [comment]
Okay, let me clean up the mess today really! 😁

**Comment by krishna-y2000** [comment]
@praveenscience Hii sir, i will finish my work of contribution.md file in next few days and will ask for merge. Let me know if any other thing you want to add.🙌

**Comment by starrohan999** [comment]
@praveenscience I actually made a poster regarding tech stack 
.
so can i raise the issue and pull it

**Comment by starrohan999** [comment]
I am really want looking forward to contributing.

**Comment by praveenscience** [comment]
@starrohan999 Can you share it here?

**Comment by rebs-becca15** [comment]
Hello Sir

I am a participant of GSSOC'21 and I would like to work on the content of README.md. There are many references to Winter of Code, I can revise it to GSSOC and I can also add some FAQs regarding GSSOC'21.

**Comment by praveenscience** [comment]
@rebs-becca15 Thanks for your message, I messaged in the Discord - I am currently cleaning up the repo right now. Once done, I'll let you all know! Max by tonight - UK time it will be done. 😊  In the meantime, can you come to #48 and see if you can help us?

**Comment by ArchishmanSengupta** [comment]
@praveenscience is there any link to the website like gh-pages? inside the README file? i can't see that

**Comment by praveenscience** [comment]
@ArchishmanSengupta It's in localhost dude, I am building that too. 😊

**Comment by praveenscience** [comment]
Folks, everyone, please check out the ReadMe! 😊

**Comment by praveenscience** [comment]
We'll create a new issue for this one. We need to discuss a lot.
