### ISSUE TITLE
Tech Stack Poster

### ISSUE THREAD

**Issue by starrohan999** [praveenscience/Internship-LMS-FrontEnd#49]
**Tech Stack Poster**
recently I read the README file I found some kind of missing thing so here is the first thing after every main point we can add a poster of that point so, everyone can easily understand and this is more beneficial also make it colorful.
@praveenscience  please assign me

**Comment by starrohan999** [comment]
please @praveenscience  assign to me.

**Comment by starrohan999** [comment]
in which file i have to add this image poster?

**Comment by praveenscience** [comment]
@starrohan999 Let's wait for designs, then I'll tell you?

**Comment by starrohan999** [comment]
Thank you for assigning me this issue you are an awesome mentor @praveenscience 
ok, @praveenscience I will wait.

**Comment by praveenscience** [comment]
@starrohan999 You saw the expectations right? Make sure you get something of that level! 😊

**Comment by starrohan999** [comment]
Definitely, I will give my 100%

**Comment by praveenscience** [comment]
Please check out the ReadMe! 😊

**Comment by simranbhalla3** [comment]
I am participant in GSSOC'21.Can you please assign this to me?

**Comment by praveenscience** [comment]
@simranbhalla3 Show me some of your designs. This one's a low priority and has already been assigned to @starrohan999. Please read the ReadMe once and also let me know if you have any questions.

**Comment by praveenscience** [comment]
@simranbhalla3 and @starrohan999 If we don't have the bandwidth to work on this, it's totally fine. We can deprioritize this... 😁 We can do it later, okay? Let me know, by tonight, I'm planning to close this issue.

**Comment by starrohan999** [comment]
sorry, @praveenscience  sir for the irregularity.
I will show all my designs at 3 pm

**Comment by praveenscience** [comment]
No update, so closing this. We'll again open it, once we're clear with the product, okay? So don't worry, you're the poster designer for us @starrohan999! 😁

**Comment by starrohan999** [comment]
@praveenscience  sir how is this poster look for the front end?
![Tech Stack Front end](https://user-images.githubusercontent.com/71714344/111978326-c92cab80-8b29-11eb-94ab-e3be07736e9b.png)

**Comment by praveenscience** [comment]
Actually looks really cool. 🔥

**Comment by starrohan999** [comment]
I also made it for backend and deployment .
