### ISSUE TITLE
Let's create a Code of Conduct Document.

### ISSUE THREAD

**Issue by Sloth-Panda** [praveenscience/Internship-LMS-FrontEnd#5]

**Comment by Sloth-Panda** [comment]
if this file needs to be added let me know

**Comment by ProPratik1405** [comment]
What should be there in this File and how can i Help?

**Comment by lokeshvenkatesan** [comment]
Kindly allocate this issue 5 to me.

**Comment by praveenscience** [comment]
Let's discuss if we need to add it in the contribution itself. Coz the contribution does have a CoC.

**Comment by tharunc** [comment]
Can you please assign me this issue ?

**Comment by Pranjal-2001** [comment]
Could you please assign it to me?

**Comment by atharvagadkari05** [comment]
I would like to make some changes in code of conduct.
Can you please assign me???
