### ISSUE TITLE
Add in let's discuss

### ISSUE THREAD

**Issue by kanchi12P** [praveenscience/Internship-LMS-FrontEnd#58]
**Is your feature request related to a problem? Please describe.**

I would like to add something more in the let's discuss part of readme file.

**Describe the solution you'd like...**

I think it would be better if add a table indicating the days assigned to assignee for solving the issue and making pr on the basis of hardness level like 1 day for level 0, and so on (the no. number of days that you would suggest).so that after that timeline it can be assigned to another participant if the former is unable to solve.

**Additional context**

I am gssoc'21 participant.
please assign it to me.

**Comment by sawantvikram** [comment]
I am gssoc'21 participant.
please assign it to me.

**Comment by praveenscience** [comment]
Actually this is a good idea. Let me check the discussions on how it is going. The Readme is not for like dev - it's for you all to plan. 😊
