### ISSUE TITLE
Add a welcome bot

### ISSUE THREAD

**Issue by itsIapetus** [praveenscience/Internship-LMS-FrontEnd#59]
**Is your feature request related to a problem? Please describe.**

I would like to add a welcome bot for students opening their first issue or PR.
Kindly assign it to me under GSSOC, thanks!

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by simranbhalla3** [comment]
I am participant in GSSOC'21.Can you please assign this to me? @praveenscience

**Comment by Jassi10000** [comment]
@itsIapetus Can you pls elaborate and answer all the questions  on how you gonna approach this , this way it will be easy for both for you and people who visit the issue ?

**Comment by praveenscience** [comment]
@simranbhalla3 Please explain what you understood and what is your approach, happy to assign you if you are having the right thought! 😊

**Comment by praveenscience** [comment]
Also @itsIapetus Isn't it already there? 🤔
