### ISSUE TITLE
Make New and Improved Readme

### ISSUE THREAD

**Issue by praveenscience** [praveenscience/Internship-LMS-FrontEnd#60]
Hey folks, Welcome to GSSoC.

This is going to be the first issue, a major one at least, after a lot of planning. Let's try to create the best Readme for our project possible. Remember, this is an **Open Source Product**. So, let's start with a couple of ideas.

Please, tell me what all sections and information we can include in the ReadMe document before claiming the issue blindly. Blind claim requests not entertained and will be rejected outright! 😅

> So far I thought about these:
>
> Heading
> Logo / Banner
> ««« Some nice badges: Add number of stars, number of contributors, beginner friendly, tech stack, etc. »»»
> - Introduction
>   - Motivation
>   - Methodology
>   - Video Links
>      - Intro Video (https://rb.gy/cygmlf)
>      - GSSoC 21 Series (https://rb.gy/o7lwj8)
>      - BrainStorming Day 1: Project Plan (https://rb.gy/dfxjnd)
>      - BrainStorming Day 2: Scrum Masters (TBD)
>   - Resources
>      - OpenSource Intro (https://rb.gy/dxnv5y)
>      - 30 Days of React (Event: https://rb.gy/zsgyja, PlayList: https://rb.gy/cxk3ek)
> - GSSoC Participation
>   - GSSoC Logo (https://i.imgur.com/BR9Q5Pd.png)
>   - Rules of GSSoC 21
>   - Levels & Points
> - Product Information
>   - Screenshots
> - Tech Stack
> - Installation & Running
> - Team
>   - Admin & Mentors
>   - Scrum Masters
>   - Contributors List
> - Contribution Guidelines

Please feel free to let me know what all we can add, this will give you more chance for getting this assigned to you. Let's have a fair assignment for this. Also, this is going to be One Person's work, so it will be assigned for only one person. 😁

Up for grabs! ✋🏻

**Comment by iamharsh1312** [comment]
Scrum Master's list can be added

**Comment by iamharsh1312** [comment]
The  methodology can be included in the list

**Comment by iamharsh1312** [comment]
Usage , badges can also be included

**Comment by praveenscience** [comment]
@iamharsh1312 What does it mean by usage? Badges like?

**Comment by iamharsh1312** [comment]
@praveenscience  On some READMEs, you may see small images that convey metadata, such as whether or not all the tests are passing for the project. You can use Shields to add some to your README. Many services also have instructions for adding a badge.
Usage from what I mean is to show the expected output

**Comment by Cgoyal48** [comment]
We can give a description of what a specific label which we are going to use signifies in that way it will be good for those who are new to open source

**Comment by ayush461** [comment]
@praveenscience Photos of running and installing code should be added for better understanding,admins and mentors photo can too be added, what's say??

**Comment by praveenscience** [comment]
Wow, thanks folks, updated the initial one. Let's make it awesome! Who's doing which? Should I split between you all? Or how should we go about? 😁

(Now comes the hard part of giving to who!)

**Comment by ayush461** [comment]
As you say SIR. @praveenscience

**Comment by dcs-soni** [comment]
Hey @praveenscience I think we can add the amount of work done, future changes or some new ideas that we are planning to add in this project.

**Comment by praveenscience** [comment]
@dcs-soni Any examples for that? Interesting, but I haven't seen something like this. But why that in Readme?

**Comment by ayush461** [comment]
@praveenscience At the top of readme,we can add project logo

**Comment by praveenscience** [comment]
@ayush461 That reminds me, we need a logo banner. I'll add an issue. So far I have got this, I like it, but yea, suggestions welcome.

![internship](https://user-images.githubusercontent.com/1830380/111150758-65810c00-8586-11eb-8941-7985fb66f23c.png)

![InternshipBG](https://user-images.githubusercontent.com/1830380/111150762-674acf80-8586-11eb-8b5c-9cf0bb3c7c09.png)

**Comment by dcs-soni** [comment]
> @dcs-soni Any examples for that? Interesting, but I haven't seen something like this. But why that in Readme?

Any newcomer to this repo will be able to identify easily about the work that is being currently done and if we include some ideas that we are planning to do in future so anyone can come up with ideas for the same. Just a thought for this project.

**Comment by praveenscience** [comment]
@dcs-soni I'll do one thing, I'll give this part of the ReadMe for you! 😅 Simple. I don't understand, but let me add this for you.

**Comment by dcs-soni** [comment]
Okay let me see if this goes well or we'll dump this one 😅

**Comment by praveenscience** [comment]
Nowwwww the question is, who should be assigned for this? I guess we have got a decent understanding of what needs to be in the Readme, can we have the first person to claim this now? (Would be great from the above people).

**Comment by ayush461** [comment]
ME

**Comment by Komal-99** [comment]
We can add one section having helpful links like getting started with Git hub and git bash .. , your merge conflicts video link.
Will help the new comers :)

**Comment by praveenscience** [comment]
@Komal-99 It's there in the resources. 😊

**Comment by praveenscience** [comment]
@ayush461 Issue is yours... Please try finishing max by today. Then if you have made any mistakes, we'll ask others to jump in and let them have their chance. OKay?

**Comment by ayush461** [comment]
OK

**Comment by ayush461** [comment]
@praveenscience sir, here do I have to write my own content under the given subtopics??

**Comment by praveenscience** [comment]
@ayush461 Remove everything in the current Readme and try to focus on creating this structure:

> Heading
> Logo / Banner
> ««« Some nice badges: Add number of stars, number of contributors, beginner friendly, tech stack, etc. »»»
> - Introduction
>   - Motivation
>   - Methodology
>   - Video Links
>      - Intro Video (https://rb.gy/cygmlf)
>      - GSSoC 21 Series (https://rb.gy/o7lwj8)
>      - BrainStorming Day 1: Project Plan (https://rb.gy/dfxjnd)
>      - BrainStorming Day 2: Scrum Masters (TBD)
>   - Resources
>      - OpenSource Intro (https://rb.gy/dxnv5y)
>      - 30 Days of React (Event: https://rb.gy/zsgyja, PlayList: https://rb.gy/cxk3ek)
> - GSSoC Participation
>   - GSSoC Logo (https://i.imgur.com/BR9Q5Pd.png)
>   - Rules of GSSoC 21
>   - Levels & Points
> - Product Information
>   - Screenshots
> - Tech Stack
> - Installation & Running
> - Team
>   - Admin & Mentors
>   - Scrum Masters
>   - Contributors List
> - Contribution Guidelines

Later on we'll think about other stuff. Anything that you don't know, just let me know. You can leave them blank.

**Comment by ayush461** [comment]
@praveenscience ok,got it.
