### ISSUE TITLE
Bug report in readme file

### ISSUE THREAD

**Issue by agamgupta2015** [praveenscience/Internship-LMS-FrontEnd#62]
**Spelling mistake**

**Comment by praveenscience** [comment]
Thanks for the contribution. This is not something we expected. We're following English India / British English here. 😊  Please tell me if you have actually seen how we are contributing and our plans? Let me know. Also why did you raise a PR before getting an approval?

**Comment by praveenscience** [comment]
This is wrong on many levels:

**Isssue**

- Issue created for no reason.
- Didn't discuss with the Project Admins or Mentors about why should this be fixed.
- We have a plan, the person didn't follow it.
- If this is just for points, then this person should be warned.

**Pull Request**

- PR made even before getting approval.
- PR fixes S to Z, when we follow Indian English / British English.
- PR made before getting the issue assigned to the developer.
- PR makes no sense.

**Comment by praveenscience** [comment]
@agamgupta2015 Please go through this: [**GSSoC 21 Series**](https://rb.gy/o2ve8n). You'll understand how bad this PR is.
