### ISSUE TITLE
ReadMe: Add the Methodology Section

### ISSUE THREAD

**Issue by praveenscience** [praveenscience/Internship-LMS-FrontEnd#67]
Can we please have an expansion of the Methodology section in the ReadMe? Make sure you include these:

- [My Experience on Spotify Agile Methodology](https://blog.praveen.science/my-experience-on-spotify-agile-methodology/)
- [Git Standards followed in our way of Spotify Agile Methodology](https://blog.praveen.science/git-standards-followed-in-our-way-of-spotify-agile-methodolgy/)

We're using **Spotify Agile Methodology**. Let's discuss what you're planning to write before you're being assigned! 😁

Up for grabs! ✋🏻

**Comment by vismitap** [comment]
I would like to work on this issue! Please assign me this issue as a part of GSSoC'21!😇

**Comment by praveenscience** [comment]
@vismitap Would you like to discuss how we are gonna go with this? 😊

**Comment by vismitap** [comment]
> @vismitap Would you like to discuss how we are gonna go with this? 😊

Yeah sure, reading the ref right now. Give me sometime to come up with something awesome! ✌

**Comment by praveenscience** [comment]
@vismitap I know you'll come up with something awesome. 😊

**Comment by vismitap** [comment]
@praveenscienceI think we can include these points:
1) We are following high alignment and high autonomy model. So, the issues created will have description of the problem to be solved, the participants have to figure out how they would like to solve it and what tool they would like to use.
2) Everything needs to be communicated to the scrum masters/project admin on what they think about a particular issue and its possible solution.
3) We can have a sprint of 3days-5days based on the level of difficulty of the issue with regular sprint planning sessions and daily stand-ups on discord (Here we can add a link to discord. But I have 1 question here🤔, do you have your own discord channel / should we add the GSSOC channel link here?).

 This is just the basic idea, I will definitely write these things in a bit more detail with the links you provided. Please give me some inputs on what more points I should add. 😅

**Comment by praveenscience** [comment]
Okay cool, the issue is yours. Let's refine it when you send it over. ✋🏻
