### ISSUE TITLE
ReadMe: Add the Rules of GSSoC 21 Section

### ISSUE THREAD

**Issue by praveenscience** [praveenscience/Internship-LMS-FrontEnd#68]
Let's have a quick overall steps about GSSoC 21. We'll include the following in the best way possible.

- Need to be already registered for GSSoC '21.
- Can't register right now again.
- Make sure you discuss in Discord before working on issue.

Let's discuss what you're planning to write before you're being assigned! 😁

Up for grabs! ✋🏻

**Comment by deephunt3r** [comment]
Can I work on this as participant of GSSOC’21

**Comment by praveenscience** [comment]
@deephunt3r Would you like to discuss how we are gonna go with this? 😊

**Comment by deephunt3r** [comment]
> @deephunt3r Would you like to discuss how we are gonna go with this? 😊

I would like to add rules you mentioned in the issue and some more like 1.Don't harass or insult any other members. Serious action will be taken if reported.
(This includes threats, internet attacks, gender-based insults and cyber bullying.)
2. Please wait until the issue get assigned to you
Is it enough or will you add more?
Can I work on it

**Comment by praveenscience** [comment]
Yea, looks good, make sure to include the working process, etc. - don't pick up issue already assigned, start work after assigning issue, before creating pr discuss on discord.
