### ISSUE TITLE
ReadMe: Add Trailer Information for GSSoC.

### ISSUE THREAD

**Issue by praveenscience** [praveenscience/Internship-LMS-FrontEnd#69]
We need to add the trailer link to the ReadMe in some nice place, with a great write up.

[**Introduction to DevTernShip**](https://rb.gy/cygmlf)

Let's discuss about the write up here before getting assigned. ✋🏻 To request for an assignment, can you write a simple pitch for this? Like where would you like to add, what would you write, etc. 🤘🏻

Choose one from these. We have got the image assets here:

- [Album](https://imgur.com/a/wspsY0Q)
   - [Welcome Instructions to GSSoC](https://i.imgur.com/SKUu62d.png)
   - [Introduction Video](https://i.imgur.com/9gZXnnt.png)
   - [Questions Answered](https://i.imgur.com/dJdVoN4.png)
   - [DevTernShip: Day 1 Talks](https://i.imgur.com/NQdx7Oj.png)
   - [DevTernShip: Scrum Masters Meeting](https://i.imgur.com/rHUvLFj.png)

Up for grabs! ✋🏻

**Comment by IdealisticINTJ** [comment]
I would like to write the introduction. The vision and the mission of the project, along with some details on the tech stack.

**Comment by praveenscience** [comment]
Go for it! @IdealisticINTJ

**Comment by NidhiSingh0068** [comment]
I would like to write about the day-1, which would be including all the discussions done during the live stream, about the technologies and features we came up with to be implemented and why we choose that....like why we are using MySQL instead of MongoDb and also the Agile approach.

**Comment by praveenscience** [comment]
@NidhiSingh0068 and @IdealisticINTJ Should we say whoever comes first be getting the points? Or should we allow one from @IdealisticINTJ and one from @NidhiSingh0068?

**Comment by NidhiSingh0068** [comment]
So every point has to be assigned to a single person?

**Comment by NidhiSingh0068** [comment]
As it is mentioned, choose one from these .

**Comment by praveenscience** [comment]
Didn't get you Nidhi. I was wondering, let's do this way. The first proposal by him, let's wait till he finishes. Then you add on to it okay?

**Comment by NidhiSingh0068** [comment]
Okay !!

**Comment by IdealisticINTJ** [comment]
@praveenscience I thought it was one of the above-mentioned that needs to be taken. 
Okay, I'll get to it.
P.S: It's a 'she'.

**Comment by NidhiSingh0068** [comment]
@IdealisticINTJ I also thought the same.

**Comment by varshith-k** [comment]
Any more goodfirst issues?

**Comment by praveenscience** [comment]
@IdealisticINTJ Start with your proposal, after that we'll give @NidhiSingh0068 a chance, to do her magic. Okay?
@varshith-k Many! Coming up.

**Comment by IdealisticINTJ** [comment]
Please review it and inform me of necessary changes so that I can make a PR as soon as possible. And, I have a question- Where exactly is this supposed to be added?
The proposal:

Welcome to the Internshipception!
Created by the developers, for the developers and the enterprises, DevTernShip aims to automate a process that is usually beset by difficulties; The recruitment phase is riddled with disorientation and this makes it difficult for the onboarding interns to make heads or tails of the system. Here's where DevTernShip jumps into the picture - By Onboarding the interns on the project in as simple a UI as possible, we ensure that all is smooth sailing.

**Comment by praveenscience** [comment]
@IdealisticINTJ How about putting this right above the Introduction heading and below the badges? Just go ahead and create a PR...

@NidhiSingh0068 I know you can do more of a magic after the PR has been accepted and we can close this issue! ✋🏻
