### ISSUE TITLE
ReadMe: Add Installation and Running Section

### ISSUE THREAD

**Issue by Spring-dot** [praveenscience/Internship-LMS-FrontEnd#72]
Can I add this section? @praveenscience

**Comment by praveenscience** [comment]
Not yet, as we're still in the design part. But yes you can do it. 😊

**Comment by Nishayadav-bit** [comment]
can i work on it

**Comment by praveenscience** [comment]
@Nishayadav-bit Did you read the above comment? Let me know. 😊

**Comment by Spring-dot** [comment]
As we will be working with react and npm, we can add steps and commands for installing npm and packages we will be working with as well as how to start react project after cloning?
Since we have not yet started with the development part, I am not sure should I add now these points or in the coming week?
@praveenscience Let me know, what to do?

**Comment by praveenscience** [comment]
@Spring-dot Yes, we are totally unclear at this point. So let's wait till the tech stack gets started, after that we'll add it. I said this is gonna be for you to write. So don't miss the Live Stream today or tomorrow, okay? Not sure what Nisha is upto, can you ask her what she's planning to do?
@Nishayadav-bit Any update? 😊

**Comment by Spring-dot** [comment]
@praveenscience okay, I will be joining the live stream.

**Comment by Nishayadav-bit** [comment]
@praveenscience  in installation and running section we can add installing process and how to start doing projects.

**Comment by praveenscience** [comment]
@Nishayadav-bit Yes, Nisha, tell me what are you planning to write there. Do you know what needs to be written there? 😊  Can you tell me here?

**Comment by Nishayadav-bit** [comment]
@praveenscience ok , tell me what would your team or project expect from me ?
  And currently i,m fresher in open source so little bit idea about it .

**Comment by praveenscience** [comment]
@Nishayadav-bit Did you come and talk to any of us before blindly asking to assign? Tell me if you have watched the following:

- [Intro Video](https://rb.gy/cygmlf)
- [GSSoC 21 Series](https://rb.gy/o7lwj8)
- [BrainStorming Day 1: Project Plan](https://rb.gy/dfxjnd)
- [BrainStorming Day 2: Scrum Masters](https://rb.gy/zwxe6g)

If yes, you might have not got this! 😊

**Comment by praveenscience** [comment]
@Nishayadav-bit In case, if you wanna do something quick and simple, just adding one line - remember, no points for this, just to practice, you can try this PR right now. But next time, speak to us in the Discord channel. 😊 

Will you pick this one: https://github.com/praveenscience/Internship-LMS-FrontEnd/issues/83?

**Comment by praveenscience** [comment]
@Spring-dot If you're here on the Live Stream, you may start working on this or this might go to another person who's claiming in the Live Stream. We need the following:

- System Requirements
- Installation & Setup
- Running the Code

Is there anything else that can be added?

**Comment by Elizah550** [comment]
Yay!!
I wanna Pick it up 
Thanks !!!

**Comment by AshuKV** [comment]
Hey, Please assign it to me.

**Comment by praveenscience** [comment]
@Elizah550 Wins it. 😊 You have 10 hours to finish this.

**Comment by Spring-dot** [comment]
@praveenscience I am having practical class, so cannot attend live stream, can I continue work on this?

**Comment by praveenscience** [comment]
@Spring-dot Yes, exams come first! I asked everyone and @Elizah550 as well, and I'd like to reassign it to you back. @Elizah550 I'll find something nice for you! 👍 

![image](https://user-images.githubusercontent.com/1830380/111765818-bb162b00-889c-11eb-8648-bb6e3f79e87a.png)

**Comment by Spring-dot** [comment]
Thanks @praveenscience, I will finish it within deadline.

**Comment by praveenscience** [comment]
@Spring-dot We're discussing and fighting for your rights, you should come and check out the [Live Stream](https://rb.gy/dxbpze) after your class.
