### ISSUE TITLE
We can add "Get in touch section" in the footer.

### ISSUE THREAD

**Issue by ASHISH-GITHUB2495** [praveenscience/Internship-LMS-FrontEnd#76]
**Features that we can add**
We can have a footer with Get in touch section ... you have option to fill name, email and message which will go directly to the admin.
Like the screenshot i have attach ...
if you like the idea I would like to contribute as GSSOC'21 participant.

**Screenshot**
![Screenshot (15)](https://user-images.githubusercontent.com/57385079/111493745-ddf0f400-8763-11eb-9a88-469521970021.png)

**Comment by praveenscience** [comment]
Yes, I like the idea, but since we're in the design phase, let's take it forward. This is nice. We are not yet implementing this. 😊 Is that okay when we start work after design?

**Comment by ASHISH-GITHUB2495** [comment]
**Sure sir ... No problem**

**Comment by Shivangi-27** [comment]
![image](https://user-images.githubusercontent.com/72151453/128812841-a4bbbcbf-5fa7-4eba-b8ca-8273727504ab.png)
 We can create our footer like this also and adding a newsletter part above the social media icons

**Comment by praveenscience** [comment]
Nice. But we don't have any app at all right, @Shivangi-27?

**Comment by Shivangi-27** [comment]
Yaa, we can improvise it. This is a demo footer that I made for my website.

**Comment by praveenscience** [comment]
Yea, try your magic @Shivangi-27

**Comment by swathi-469** [comment]
If the issue is available or others not working on it .. I can do it

**Comment by kashishkhaneja** [comment]
Hello,
I am Kashish Khaneja, I want to work on this issue.
 Will be adding a footer with all the social handles and the contact us button for the queries. Also, will add a side bar for social handles.
Is this issue still available?

**Comment by praveenscience** [comment]
@swathi-469 @kashishkhaneja Please continue... 🔥

**Comment by kashishkhaneja** [comment]
> @swathi-469 @kashishkhaneja Please continue... 🔥

For the get in touch part, I have added a Contact us button linked to Gmail. 
@swathi-469 can you get in touch with me on linked. Have sent you a connection request. For your reference, I am attaching the screenshots of changes made by me in pull request#134.
![Edit](https://user-images.githubusercontent.com/61909674/133292639-abb24154-9739-4dd9-ba14-39eae5cd6ce1.png)
