### ISSUE TITLE
Designing basic wireframes for the website

### ISSUE THREAD

**Issue by Spring-dot** [praveenscience/Internship-LMS-FrontEnd#81]
We need the complete user flow for this platform. Let's design it using the software of your choice. This should cover:

* Welcome
* Landing Page
* Sign In
* Help Screens
* User Dashboard
  * User Profile
  * User Account Settings
* Admin Dashboard
  * Manage Users
  * Manage Content
    * Steps Management

**Comment by praveenscience** [comment]
Cool, let's discuss with the other designers too? 😊

**Comment by praveenscience** [comment]
Can you try talking to Deepak and Devraj about this? Off to a good start then! ✋🏻

**Comment by praveenscience** [comment]
Cool, let's discuss with the other designers too? 😊
Can you try talking to Deepak and Devraj about this? Off to a good start then! ✋🏻

**Comment by Spring-dot** [comment]
@praveenscience who is working on wireframes? Have we completed this part? Sorry I missed last week updates.

**Comment by praveenscience** [comment]
@Spring-dot Those two: Deepak and Devraj

**Comment by Spring-dot** [comment]
I will work on this.

**Comment by srishtij2000** [comment]
Can I work on this issue?

**Comment by praveenscience** [comment]
@srishtij2000 Yes, please... Start the work... 🔥

**Comment by Deepak-dex** [comment]
May i also work on this ?

**Comment by praveenscience** [comment]
@Deepak-dex You have to! 😅

**Comment by Spring-dot** [comment]
https://drive.google.com/drive/folders/124rjjknUg7rF-TQY_ojUjBjEDrzD464Y?usp=sharing
In this drive I have added few designs, please go through this and  @Deepak-dex  @srishtij2000 you people can also add your files here, It will be easy for everyone to track our work. I was not able share link on discord :( 
Rest, Can any mentor tell in user account setting what we are planning to do? For that page I am confused

**Comment by srishtij2000** [comment]
Okay okay thankyou

**Comment by Insomaniacgamer** [comment]
@praveenscience am loving the designs should we approve them ?

**Comment by srishtij2000** [comment]
Please check my design and kindly give the feedback

**Comment by srishtij2000** [comment]
Kindly give the feedback so that I can make the changes accordingly in the rest of the designs also

**Comment by praveenscience** [comment]
@srishtij2000 Just came out of meeting... Lemme check...

**Comment by praveenscience** [comment]
@srishtij2000 Where's your design?

**Comment by srishtij2000** [comment]
In the drive 
https://drive.google.com/drive/folders/124rjjknUg7rF-TQY_ojUjBjEDrzD464Y?usp=sharing

**Comment by praveenscience** [comment]
Oh, okay, I didn't know you have added something too. Let me check...
/cc @Insomaniacgamer

**Comment by praveenscience** [comment]
@Spring-dot @Deepak-dex @srishtij2000 
Other than the User Profile page, everything seems to be okay... Let's create a flow... :) Any XD or Figma people? Can you make it better? Consistent with the design?

**Comment by srishtij2000** [comment]
I can make it with Figma

**Comment by srishtij2000** [comment]
This was only the wireframe

**Comment by praveenscience** [comment]
Cool, please carry on... In Figma, we'll be able to see how it looks or everything like flow, etc.

**Comment by srishtij2000** [comment]
Okay so I'll make it with Figma.

**Comment by srishtij2000** [comment]
https://www.figma.com/file/9BExnBjnU7fRaupNajbLXa/Project?node-id=0%3A1
I have made the user dashboard wireframe using figma. Kindly check and give the feedback.

**Comment by praveenscience** [comment]
@srishtij2000 Mainly we asked for figma is for the flow diagram... Let me share you a sample... 🚀

**Comment by srishtij2000** [comment]
This file is not opening

**Comment by praveenscience** [comment]
> This file is not opening

Do you have Figma with you?

**Comment by srishtij2000** [comment]
Yes

**Comment by srishtij2000** [comment]
But I use the windows app

**Comment by Spring-dot** [comment]
@praveenscience I will update tomorrow with the flow diagram. @srishtij2000 any progress?

**Comment by srishtij2000** [comment]
I am unable to figure out that how can I make a flow diagram so can anyone please help me?

**Comment by praveenscience** [comment]
@Spring-dot Can you help @srishtij2000? Can we please finish it by today? 😢 
/cc @Insomaniacgamer

**Comment by srishtij2000** [comment]
@Spring-dot please help I am still stuck

**Comment by Spring-dot** [comment]
@srishtij2000 I have already made the design, check the discord channel.

**Comment by Insomaniacgamer** [comment]
@Spring-dot please link up here too , loosing context in discord is too easy
// cc @praveenscience

**Comment by Spring-dot** [comment]
Flow map: https://drive.google.com/file/d/1oNx0eAEpnyqtqz17votFGa7UD9SOK9nl/view?usp=sharing
Design: https://balsamiq.cloud/s165djm/pcggtav

**Comment by saimanoharhm** [comment]
@praveenscience Sir, Could you please assign this to me.

**Comment by Insomaniacgamer** [comment]
@Spring-dot can you share design in any other more secure platform ?

**Comment by SnehaVeerakumar** [comment]
I would like to join the people here :)
