### ISSUE TITLE
ReadMe: Add Day 3 Video Link

### ISSUE THREAD

**Issue by praveenscience** [praveenscience/Internship-LMS-FrontEnd#83]
Very quick one for whoever is trying out Open Source for the first time, can someone add the Video 3's link for tomorrow?

```
- [Tech Setup Day 3](https://rb.gy/dxbpze)
```
Just remember, this is just for practice, no points will be awarded or no labels will be added. If you wanna practice, I can assign you. 😊 

Up for grabs! ✋🏻

**Comment by gaurav24072002** [comment]
yah ! sure I'll do it 😄

**Comment by praveenscience** [comment]
@gaurav24072002 Wait for some time... I am waiting for @Nishayadav-bit to pick this up. If she doesn't pick it up by tomorrow, you can do it. 😅

**Comment by Nishayadav-bit** [comment]
Yes I will do it

**Comment by gaurav24072002** [comment]
ok

**Comment by praveenscience** [comment]
@Nishayadav-bit Check what @gaurav24072002 did and see what I said in the comments. #84. Just follow the same. It's yours. Finish it in 10 mins please.
