### ISSUE TITLE
Set up the basic App and Routing

### ISSUE THREAD

**Issue by DevrajDC** [praveenscience/Internship-LMS-FrontEnd#86]
Hey @praveenscience, please create these as a base to work on:

- Environment Setup
- Project Setup
- Husky Setup
- React Basics
- Router Setup
- Skeleton for Files

**Comment by praveenscience** [comment]
Let's fix the rest tomorrow or soon! 😊

**Comment by ShambhaviSharma0110** [comment]
Hey I'd like to work on this please assign me....

**Comment by praveenscience** [comment]
@ShambhaviSharma0110 Are you really serious about this? 😅

**Comment by praveenscience** [comment]
@ShambhaviSharma0110 Are you really serious about this? 😅 If yes, let's do it together on the Live Stream then! ✋🏻

Can you sign up as a [Co-Host](https://events.praveen.science/30-days-of-react/) here?

**Comment by praveenscience** [comment]
@ShambhaviSharma0110 Still interested? 🤔

**Comment by ShambhaviSharma0110** [comment]
@praveenscience I'll create a pr tomorrow if it gets merged then you can take a look at it

**Comment by praveenscience** [comment]
@ShambhaviSharma0110 Are you really reading my comments and are you actively participating in the channel discussions about this? This one's a part of GSSoC 21 right? Also, what do you mean by "if it gets merged then you can take a look at it"?

**Comment by ampsteric** [comment]
Hi @praveenscience long time no see.
please let me know if this is still pending , I would surely want to give it a try.

**Comment by praveenscience** [comment]
@ampsteric Sorry, it's been done. 🔥
