### ISSUE TITLE
for contacting Email id should be provided

### ISSUE THREAD

**Issue by tanya070820** [praveenscience/Internship-LMS-FrontEnd#87]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like...**

**Describe alternatives you've considered?**

**Approach to be followed (optional):**

**Additional context**

**Comment by praveenscience** [comment]
@tanya070820 Are you in the [Live Stream](https://rb.gy/dxbpze)? Why did you raise this issue before discussing? Let's discuss one to one.
