### ISSUE TITLE
Creation of pr template

### ISSUE THREAD

**Issue by Sloth-Panda** [praveenscience/Internship-LMS-FrontEnd#9]
Can I add a pr template??

**Comment by praveenscience** [comment]
I guess we do have one... I just saw a PR about it. Can you kindly check #8, and if it doesn't address it, then this issue is yours! Let me know after checking it.

**Comment by Sloth-Panda** [comment]
@praveenscience  sir that's different an issue template is different from  a pr template

**Comment by praveenscience** [comment]
It's yours man... Go for it.
