### ISSUE TITLE
ReadMe: Add FAQ Section

### ISSUE THREAD

**Issue by dudenayak** [praveenscience/Internship-LMS-FrontEnd#95]
**I was looking forward to add FAQs Section in the ReadMe file.**

**Comment by riyaverma338** [comment]
Hi, I would like to work on this.

**Comment by raks924** [comment]
hey can i work on this?

**Comment by praveenscience** [comment]
@dudenayak It's all yours.
@riyaverma338 and @raks924 I'll find you both something nice - please message me on Discord channel. 😊

**Comment by rk05-lenavo** [comment]
sir I'm the participant of GSSOC'21. Can you please assign me this issue.

**Comment by praveenscience** [comment]
@rk05-lenavo Please tell me what are you planning to do? 😁

**Comment by rk05-lenavo** [comment]
@praveenscience Sir what I was thinking is that some information about opensource code, How to work with it including GSSOC.

**Comment by praveenscience** [comment]
@rk05-lenavo Is this not added here in this?
https://github.com/praveenscience/Internship-LMS-FrontEnd/pull/98/files

**Comment by rk05-lenavo** [comment]
@praveenscience Yup some of them. Actually sir I was thinking of including how to start with git why not to work on the master branch.

**Comment by praveenscience** [comment]
@rk05-lenavo Sure, then once this PR is completed, you can create another PR. Assigning it to you, okay? Just wait till #98 is merged, Okay?

**Comment by praveenscience** [comment]
@rk05-lenavo You're welcome.

**Comment by praveenscience** [comment]
@rk05-lenavo Start working on this.

**Comment by rk05-lenavo** [comment]
@praveenscience Okay Sir.
