### ISSUE TITLE
Design a logo for DevTernShip

### ISSUE THREAD

**Issue by preetiahuja18** [praveenscience/Internship-LMS-FrontEnd#99]
Let's see if someone can come up with a better design than what's there right now. I would really ask you to have a look at the following:

- [10 Top Logo Design Trends for 2021](https://99designs.co.uk/blog/trends/logo-design-trends/)
- [Top 20 Logo Design Trends For 2021 - Logo Design](https://www.thelogocreative.co.uk/top-20-logo-design-trends-for-2021/)
- [Logo Design Trends in 2021 to Drive you Loco | GraphicMama Blog](https://graphicmama.com/blog/logo-design-trends-2021/)
- [10 unmissable logo design trends for 2021 | Creative Bloq](https://www.creativebloq.com/news/logo-design-trends-2021)
- [Logo Design Trends 2021 designs, themes, templates and downloadable graphic elements on Dribbble](https://dribbble.com/tags/logo_design_trends_2021)

This is up for grabs! 🔥

**Comment by praveenscience** [comment]
Issues should be descriptive.

**Comment by preetiahuja18** [comment]
How's that ? @praveenscience 
![logo devternship](https://user-images.githubusercontent.com/72223546/112854309-5c865380-90cb-11eb-8f3b-192c1cc7930f.jpg)

**Comment by praveenscience** [comment]
@preetiahuja18 I have sent you a couple of inspirations to look at. 😊  This is a good attempt but best suited for early 1990s. 🤘🏻

**Comment by ishwari20** [comment]
I have also made a good logo for Devternship. @praveenscience please assign this issue to me as well.

**Comment by praveenscience** [comment]
@ishwari20 Show us what you have done! 😊

**Comment by ishwari20** [comment]
![DEVTERNSHIP](https://user-images.githubusercontent.com/56400099/112948029-28f00b80-9155-11eb-9fea-5caa50453b9c.png)

**Comment by praveenscience** [comment]
@ishwari20 I guess it's time I'll update the main issue. Kindly check the first issue comment and come back with a nice one?

**Comment by ishwari20** [comment]
Yes sir

**Comment by ayu222220** [comment]
Can you assign me? Would like to work on it Gssoc'21

**Comment by rk05-lenavo** [comment]
@praveenscience I'm the Participant of GSSOC'21.Can You Please assign me this issue.

**Comment by praveenscience** [comment]
@rk05-lenavo Assigned. Let's see what you're coming up with.

**Comment by rk05-lenavo** [comment]
@praveenscience  Sir is this okay.

 
![logo](https://user-images.githubusercontent.com/68415300/113155274-7acc8a80-9256-11eb-910f-1187e0a6449e.png)

**Comment by praveenscience** [comment]
@rk05-lenavo Okay good attempt. But can you try something attractive from the list on the top? Thanks. 😁

**Comment by rk05-lenavo** [comment]
@praveenscience Sure sir

**Comment by rk05-lenavo** [comment]
@praveenscience Sir is this Okay.
![logo1](https://user-images.githubusercontent.com/68415300/113160817-72c31980-925b-11eb-8e32-24efcacf84be.png)

**Comment by praveenscience** [comment]
@rk05-lenavo Free logo makers aren't that good. This is no where professional buddy. Can you please come up with any own designs?

**Comment by praveenscience** [comment]
People who work on this, please see this: [2021 Logo Design Inspirations](https://cdn.mos.cms.futurecdn.net/GHx7uoWJGoXYdCcVkgxjNk-970-80.png)

**Comment by rk05-lenavo** [comment]
@praveenscience okay sir I'll try again

**Comment by shobit1337** [comment]
@praveenscience Here is something I tried, Tell me how's it look? Tried logo making for the first after several hours I came up with this :sweat_smile:
![Artboard 1](https://user-images.githubusercontent.com/37979367/113505609-9341eb00-955d-11eb-882f-2954309f0047.png)

**Comment by praveenscience** [comment]
@shobit1337 Good for a banner mate. Not a logo. Looking more in terms of the initial comment. Check the trends.

**Comment by ayu222220** [comment]
![Uploading DEVINTERship.png…]()

**Comment by ayu222220** [comment]
![DEVINTERship](https://user-images.githubusercontent.com/65357585/113507153-66460600-9566-11eb-8d60-ad5c1ebc4c69.png)

**Comment by Elizah550** [comment]
Hey folks can I try it ? . Is the issue done or still incomplete ?

**Comment by praveenscience** [comment]
@Elizah550 Go on... 😊  Please...

**Comment by NemaVatsala** [comment]
@praveenscience I'm a Participant of GSSOC'21.Could i try this as well?

**Comment by praveenscience** [comment]
@NemaVatsala Yes please. 🔥

**Comment by ayu222220** [comment]
> @praveenscience please tell me about this and any changes you would like
> 
> ![DEVINTERship](https://user-images.githubusercontent.com/65357585/113507153-66460600-9566-11eb-8d60-ad5c1ebc4c69.png)

@praveenscience  Would you review this please?

**Comment by praveenscience** [comment]
What's the difference between this and your previous submission @ayu222220? Please clarify.

**Comment by ayu222220** [comment]
Nothing, I qouted it so that you can review it.

**Comment by praveenscience** [comment]
Already reviewed. 🔥

**Comment by praveenscience** [comment]
@ayu222220 If you ask me for a feedback, please review the links in the first message. Thanks.

**Comment by ayu222220** [comment]
Sorry but it wasn't visible to me.
Can you tell me once more so that I can go for modification.
@praveenscience

**Comment by praveenscience** [comment]
@ayu222220 Please check the first message's links and see the logos, something like that.

**Comment by Elizah550** [comment]
Hey folks !! I just gave a try how is it 
![Screenshot (41)](https://user-images.githubusercontent.com/43481897/113706816-bd7ddf00-96fc-11eb-9201-9439f8229c4f.png)

**Comment by praveenscience** [comment]
@Elizah550 Actually the logo seems nice. Really.

**Comment by Elizah550** [comment]
Ok I will Thanks !!

**Comment by NemaVatsala** [comment]
> @NemaVatsala Yes, please. 🔥

![d](https://user-images.githubusercontent.com/70408681/113985930-4ebe9400-986a-11eb-857e-caf297120368.png)
I can make a few changes if required.

**Comment by praveenscience** [comment]
@NemaVatsala You just rocked it! I really love this... ❤️

**Comment by NemaVatsala** [comment]
Glad you liked it :)- its @Vatsala(P) on GS channel

**Comment by praveenscience** [comment]
@NemaVatsala There are many vatsalas... Which one are you? Tell me your full Discord ID with that 4 numbers.

**Comment by NemaVatsala** [comment]
this is the id: Vatsala#2290, 1st one

**Comment by praveenscience** [comment]
@NemaVatsala Can you raise a new section in the ReadMe: Branding and then add these logos? 😊  It's yours now.

**Comment by NemaVatsala** [comment]
Sure.

**Comment by NemaVatsala** [comment]
Sure.

**Comment by sowmiya-venkatesan** [comment]
I just love to contribute here, Do check my logos, and let me know if it is okay or not? @praveenscience 

![Devternship (3)](https://user-images.githubusercontent.com/74345706/115562714-64a16f80-a2d4-11eb-91d2-df3330a951c3.png)
![Devternship (2)](https://user-images.githubusercontent.com/74345706/115562721-65d29c80-a2d4-11eb-9963-37984532203b.png)
![Devternship (1)](https://user-images.githubusercontent.com/74345706/115562724-6703c980-a2d4-11eb-9bb8-946eaade8571.png)

**Comment by alphaX86** [comment]
The logo looks nice @sowmiya-venkatesan

**Comment by sowmiya-venkatesan** [comment]
> The logo looks nice @sowmiya-venkatesan

Thank you !!

**Comment by praveenscience** [comment]
@gargijs What do you wanna work on? 🤔  I don't understand. Maybe show some designs... 🔥
@NemaVatsala You ready any time?

**Comment by NemaVatsala** [comment]
yes, i'll try to add a PR today

**Comment by praveenscience** [comment]
@gargijs Any progress?
